package processor

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"

	"github.com/rs/zerolog/log"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	oteltrace "go.opentelemetry.io/otel/trace"

	"video-processor/internal/processor/processor-steps"
	"video-processor/internal/telemetry"
	"video-processor/metrics"
)

// Individual timeouts per pipeline step.
const (
	stepTimeoutValidate   = 30 * time.Second
	stepTimeoutAnalyze    = 30 * time.Second
	stepTimeoutTranscode  = 3 * time.Minute
	stepTimeoutThumbnails = 60 * time.Second
	stepTimeoutAudio      = 2 * time.Minute
	stepTimeoutPreview    = 2 * time.Minute
	stepTimeoutStreaming  = 4 * time.Minute

	// transferSlack covers MinIO download of the source plus upload of every
	// artifact — neither is inside a step timeout.
	transferSlack = 5 * time.Minute
)

// JobBudget returns the whole-job timeout for a given scale: every step timeout
// plus transfer slack. Steps 4-7 usually run in parallel, so this is an upper
// bound on purpose — the per-step timeouts are the real limits, this is only the
// backstop for stalls no step timeout can see.
func JobBudget(scale float64) time.Duration {
	steps := stepTimeoutValidate + stepTimeoutAnalyze + stepTimeoutTranscode +
		stepTimeoutThumbnails + stepTimeoutAudio + stepTimeoutPreview + stepTimeoutStreaming
	return scaleTimeout(steps+transferSlack, scale)
}

func scaleTimeout(d time.Duration, scale float64) time.Duration {
	if scale <= 0 {
		scale = 1
	}
	return time.Duration(float64(d) * scale)
}

// ProcessingResult contains the paths of artifacts generated by the pipeline.
// TempDir should be removed by the caller after uploads.
type ProcessingResult struct {
	TempDir       string
	ThumbnailsDir string
	AudioPath     string
	PreviewPath   string
	StreamingDir  string
	Metadata      *processor_steps.VideoMetadata
}

// Options controls performance behavior of the processing pipeline.
type Options struct {
	ParallelNonCriticalSteps      bool
	MaxParallelPostTranscodeSteps int
	HLSSingleCommand              bool
	HLSSingleCommandFallback      bool
	// VideoEncoder is processor_steps.VideoEncoderCPU or VideoEncoderNVENC (resolved before ProcessVideo).
	VideoEncoder string
	NVENCPreset  string
	// TimeoutScale multiplies every step timeout. Slow host or big files: raise it.
	// 0 means 1 (no scaling).
	TimeoutScale float64
}

// step returns the step timeout adjusted by the configured scale.
func (o Options) step(d time.Duration) time.Duration {
	return scaleTimeout(d, o.TimeoutScale)
}

// DefaultOptions returns safe defaults for the processing pipeline.
func DefaultOptions() Options {
	return Options{
		ParallelNonCriticalSteps:      true,
		MaxParallelPostTranscodeSteps: 4,
		HLSSingleCommand:              true,
		HLSSingleCommandFallback:      true,
		VideoEncoder:                  processor_steps.VideoEncoderCPU,
		NVENCPreset:                   "p5",
		TimeoutScale:                  1,
	}
}

// ProcessVideo executes all steps of the video processing pipeline.
func ProcessVideo(ctx context.Context, inputPath, outputPath string, opts Options) (*ProcessingResult, error) {
	baseDir := filepath.Dir(outputPath)
	videoBaseName := filepath.Base(inputPath)
	videoBaseName = videoBaseName[:len(videoBaseName)-len(filepath.Ext(videoBaseName))]

	tempDir := filepath.Join(baseDir, videoBaseName+"_temp")
	if err := os.MkdirAll(tempDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create temp directory: %w", err)
	}

	result := &ProcessingResult{TempDir: tempDir}

	// 1. Validation
	log.Info().Msg("Step 1/7: Validating video")
	if err := runStep(ctx, "validate", opts.step(stepTimeoutValidate), func(stepCtx context.Context) error {
		return processor_steps.ValidateVideo(stepCtx, inputPath)
	}); err != nil {
		return result, fmt.Errorf("validation failed: %w", err)
	}

	// 2. Content analysis
	log.Info().Msg("Step 2/7: Analyzing content")
	_ = runStep(ctx, "analyze", opts.step(stepTimeoutAnalyze), func(stepCtx context.Context) error {
		metadata, err := processor_steps.AnalyzeContent(stepCtx, inputPath)
		if err != nil {
			log.Warn().Err(err).Msg("Content analysis failed")
			return err
		}
		result.Metadata = metadata
		return nil
	})

	// 3. Transcoding (critical step)
	log.Info().Msg("Step 3/7: Transcoding video")
	if err := runStep(ctx, "transcode", opts.step(stepTimeoutTranscode), func(stepCtx context.Context) error {
		return processor_steps.TranscodeVideo(stepCtx, inputPath, outputPath, opts.VideoEncoder, opts.NVENCPreset)
	}); err != nil {
		return result, fmt.Errorf("transcoding failed: %w", err)
	}

	transcodedPath := outputPath

	if !opts.ParallelNonCriticalSteps {
		runNonCriticalStepsSequential(ctx, inputPath, transcodedPath, tempDir, result, opts)
	} else {
		runNonCriticalStepsParallel(ctx, inputPath, transcodedPath, tempDir, result, opts)
	}

	log.Info().Msg("Processing pipeline completed successfully")
	return result, nil
}

func runNonCriticalStepsSequential(ctx context.Context, inputPath, transcodedPath, tempDir string, result *ProcessingResult, opts Options) {
	log.Info().Msg("Step 4/7: Generating thumbnails")
	thumbnailsDir := filepath.Join(tempDir, "thumbnails")
	if err := runStep(ctx, "thumbnails", opts.step(stepTimeoutThumbnails), func(stepCtx context.Context) error {
		return processor_steps.GenerateThumbnails(stepCtx, transcodedPath, thumbnailsDir)
	}); err != nil {
		log.Warn().Err(err).Msg("Failed to generate thumbnails")
	} else {
		result.ThumbnailsDir = thumbnailsDir
	}

	log.Info().Msg("Step 5/7: Extracting audio")
	audioPath := filepath.Join(tempDir, "audio.mp3")
	if err := runStep(ctx, "audio", opts.step(stepTimeoutAudio), func(stepCtx context.Context) error {
		return processor_steps.ExtractAudio(stepCtx, transcodedPath, audioPath)
	}); err != nil {
		log.Warn().Err(err).Msg("Audio extraction failed")
	} else {
		result.AudioPath = audioPath
	}

	log.Info().Msg("Step 6/7: Generating preview")
	previewPath := filepath.Join(tempDir, "preview.mp4")
	if err := runStep(ctx, "preview", opts.step(stepTimeoutPreview), func(stepCtx context.Context) error {
		return processor_steps.GeneratePreview(stepCtx, transcodedPath, previewPath)
	}); err != nil {
		log.Warn().Err(err).Msg("Preview generation failed")
	} else {
		result.PreviewPath = previewPath
	}

	log.Info().Msg("Step 7/7: Segmenting for streaming")
	streamingDir := filepath.Join(tempDir, "streaming")
	if err := runStep(ctx, "streaming", opts.step(stepTimeoutStreaming), func(stepCtx context.Context) error {
		return processor_steps.SegmentForStreamingWithOptions(stepCtx, inputPath, streamingDir, processor_steps.HLSOptions{
			SingleCommand: opts.HLSSingleCommand,
			Fallback:      opts.HLSSingleCommandFallback,
			VideoEncoder:  opts.VideoEncoder,
			NVENCPreset:   opts.NVENCPreset,
		})
	}); err != nil {
		log.Warn().Err(err).Msg("Streaming segmentation failed")
	} else {
		result.StreamingDir = streamingDir
	}
}

func runNonCriticalStepsParallel(ctx context.Context, inputPath, transcodedPath, tempDir string, result *ProcessingResult, opts Options) {
	maxParallel := opts.MaxParallelPostTranscodeSteps
	if maxParallel < 1 {
		maxParallel = 1
	}
	if maxParallel > 4 {
		maxParallel = 4
	}

	sem := make(chan struct{}, maxParallel)
	var wg sync.WaitGroup
	var mu sync.Mutex

	run := func(name, startMsg, failMsg string, timeout time.Duration, fn func(context.Context) error, onSuccess func()) {
		wg.Add(1)
		go func() {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()

			log.Info().Msg(startMsg)
			if err := runStep(ctx, name, timeout, fn); err != nil {
				log.Warn().Err(err).Msg(failMsg)
				return
			}
			mu.Lock()
			onSuccess()
			mu.Unlock()
		}()
	}

	thumbnailsDir := filepath.Join(tempDir, "thumbnails")
	run("thumbnails", "Step 4/7: Generating thumbnails", "Failed to generate thumbnails", opts.step(stepTimeoutThumbnails), func(stepCtx context.Context) error {
		return processor_steps.GenerateThumbnails(stepCtx, transcodedPath, thumbnailsDir)
	}, func() {
		result.ThumbnailsDir = thumbnailsDir
	})

	audioPath := filepath.Join(tempDir, "audio.mp3")
	run("audio", "Step 5/7: Extracting audio", "Audio extraction failed", opts.step(stepTimeoutAudio), func(stepCtx context.Context) error {
		return processor_steps.ExtractAudio(stepCtx, transcodedPath, audioPath)
	}, func() {
		result.AudioPath = audioPath
	})

	previewPath := filepath.Join(tempDir, "preview.mp4")
	run("preview", "Step 6/7: Generating preview", "Preview generation failed", opts.step(stepTimeoutPreview), func(stepCtx context.Context) error {
		return processor_steps.GeneratePreview(stepCtx, transcodedPath, previewPath)
	}, func() {
		result.PreviewPath = previewPath
	})

	streamingDir := filepath.Join(tempDir, "streaming")
	run("streaming", "Step 7/7: Segmenting for streaming", "Streaming segmentation failed", opts.step(stepTimeoutStreaming), func(stepCtx context.Context) error {
		return processor_steps.SegmentForStreamingWithOptions(stepCtx, inputPath, streamingDir, processor_steps.HLSOptions{
			SingleCommand: opts.HLSSingleCommand,
			Fallback:      opts.HLSSingleCommandFallback,
			VideoEncoder:  opts.VideoEncoder,
			NVENCPreset:   opts.NVENCPreset,
		})
	}, func() {
		result.StreamingDir = streamingDir
	})

	wg.Wait()
}

// runStep executes a pipeline step within an OTel span and records duration via Prometheus.
// The span is marked as error if the step fails.
func runStep(ctx context.Context, name string, timeout time.Duration, fn func(context.Context) error) error {
	stepCtx, span := telemetry.Tracer().Start(ctx, "step/"+name,
		oteltrace.WithAttributes(attribute.String("step.name", name)),
	)
	defer span.End()

	stepCtx, cancel := context.WithTimeout(stepCtx, timeout)
	defer cancel()

	start := time.Now()
	err := fn(stepCtx)
	metrics.ProcessingStepDuration.WithLabelValues(name).Observe(time.Since(start).Seconds())

	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	return err
}
